### ISSUE TITLE
Any reason why this is not in the package manager yet?

### ISSUE THREAD

**Issue by sebas77** [Unity-Technologies/ReproProjectWizard#1]

**Comment by jelliot-unity** [comment]
Great suggestion! Just hadn't got around to it.

**Comment by MartinLCoatsink** [comment]
@jelliot-unity gotten around to it yet? :P 

...

Joke aside, I'm trying to create download it now, and I'm not sure what "package" that this part in the readme refers to: "Download the **Repro Wizard package** and import it into your project."

I don't see any releases, and I don't see it in the Unity package manager either. Am I supposed to just download the zip & import that "package"?

**Comment by jelliot-unity** [comment]
Sorry - It's been on my list for a while, but haven't managed to get the
spare cycles to prioritize it.

You can just download the code and drop it into your project and it'll work
just fine that way.

**Comment by 1SuratnSuriy** [comment]
https://help.github.com/articles/github-community-guidelines

**Comment by kindredkara** [comment]
Hello! A new completely updated version of Repro Project Wizard has been released as an Experimental Package, and can now be installed via the Package Manager using the name 'com.unity.repro-project-wizard'

https://docs.unity3d.com/Packages/com.unity.repro-project-wizard@0.2/manual/index.html
