### ISSUE TITLE
Custom packages are not embedded with the project

### ISSUE THREAD

**Issue by jfperusse-bhvr** [Unity-Technologies/ReproProjectWizard#2]
When internal scoped registries are used, the installed packages should be embedded under the Packages folder to simplify sharing the repro project.

**Comment by kindredkara** [comment]
Hello! 
Repro Project Wizard has been picked up by a new team and has been completely updated and released as an experimental package. The new version does support Custom Packages which can be selected to be embedded with created Repro Projects.

The new version can be installed via the Package Manager using the name 'com.unity.repro-project-wizard'

https://docs.unity3d.com/Packages/com.unity.repro-project-wizard@0.2
